# For more information: https://laravel.com/docs/sail
version: "3.7"

services:

    asterisk: 
        build:
            context: ../asterisk
            dockerfile: Dockerfile
        image: asterisk:latest
        environment:
            DB_HOST: "${HOST_ADDRESS}"
            DB_PORT: "${FORWARD_DB_PORT}"
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
            TZ: '${TIME_ZONE}'
        network_mode: host

    sipp: 
        build:
            context: ../sipp
            dockerfile: Dockerfile
        image: sipp:latest
        tty: true
        environment:
            TZ: '${TIME_ZONE}'
        volumes:
            - ../sipp/scenarios:/usr/src/SIPp
        networks:
            - sail

    laravel:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            TZ: '${TIME_ZONE}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mariadb'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            TZ: '${TIME_ZONE}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
